__lisk_groups({
  "ascend": {
    "tooltip": "Lisk Ascend Team",
    "tag": "ASC",
    "class": "md-ascend",
    "members": [
      "moosty",
      "nimbus",
      "kylefromohio",
      "crypto_embassy",
      "anamix",
      "southpaw439",
      "sdrpa",
      "liskmagazine",
      "slamper",
      "diamse"
    ]
  },
  "dutch": {
    "tooltip": "Dutch Pools",
    "tag": "DTCH",
    "members": [
      "kippers",
      "fnoufnou",
      "thamar",
      "st3v3n",
      "dutch_pool"
    ]
  },
  "gdt_sponsor": {
    "tooltip": "Sponsored GDT Members",
    "tag": "GDTs",
    "class": "md-accent",
    "members": [
      "5an1ty",
      "joo5ty",
      "vekexasia",
      "slasheks"
    ]
  },
  "gdt": {
    "tooltip": "GDT Member",
    "tag": "GDT",
    "class": "md-primary",
    "members": [
      "hirish",
      "5an1ty",
      "alepop",
      "bioly",
      "cc001",
      "corsaro",
      "dakk",
      "eclipsun",
      "forrest",
      "gdtpool",
      "goldeneye",
      "gr33ndrag0n",
      "grumlin",
      "hagie",
      "hmachado",
      "joel",
      "joo5ty",
      "kushed.delegate",
      "liskgate",
      "liskit",
      "mrv",
      "nerigal",
      "ntelo",
      "ondin",
      "philhellmuth",
      "punkrock",
      "redsn0w",
      "sgdias",
      "slasheks",
      "splatters",
      "tembo",
      "vekexasia",
      "vi1son"
    ]
  },
  "elite_support": {
    "tooltip": "Elite Supported Member",
    "tag": "ELTs",
    "class": "md-warn",
    "members": [
      "phoenix1969",
      "stellardynamic",
      "nerigal"
    ]
  },
  "elite": {
    "tooltip": "Elite Member",
    "tag": "ELT",
    "class": null,
    "members": [
      "luiz",
      "liskjp",
      "iii.element.iii",
      "rooney",
      "badman0316",
      "spacetrucker",
      "acheng",
      "someonesomeone",
      "phinx",
      "bigfisher",
      "leo",
      "luxiang7890",
      "panzer",
      "will",
      "grajsondelegate",
      "xujian",
      "eastwind_ja",
      "mrgr",
      "crodam",
      "hua",
      "honeybee",
      "carolina",
      "adrianhunter",
      "seven",
      "augurproject",
      "chamberlain",
      "liskroad",
      "savetheworld",
      "forger_of_lisk",
      "mac",
      "dakini",
      "lwyrup",
      "hong",
      "crolisk",
      "goodtimes",
      "zy1349",
      "veriform",
      "yuandian",
      "cai",
      "blackswan",
      "loveforever",
      "jiandan",
      "bilibili",
      "bigtom",
      "jixie",
      "khitan",
      "kc",
      "threelittlepig",
      "menfei",
      "china",
      "kaystar",
      "elonhan",
      "catstar",
      "carbonara"
    ]
  },
  "sherwood": {
    "tooltip": "Sherwood Member",
    "tag": "SHW",
    "class": "md-shw",
    "members": [
      "liberspirita",
      "robinhood",
      "liskpro.com",
      "phoenix1969",
      "4fryn",
      "bloqspace.io",
      "liskascend"
    ]
  }
});